### ISSUE TITLE
Allow adding issue-title

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#27]
At: http://178.62.254.91/lf/initiative/new.html?area_id=3

There is no separate field to **name** the issue (the parent for multiple initiatives).

Issue names are simply the Policy name, and then some #id number, e.g. `Resolution #54`.

We'd like a name-field for an issue (probably not in the Database as well, hope it's possible?) which then replaces the `Resolution #54` title!

Same appearance as initiative-title (but then an `.issue-title` class added):

```
What is the goal of your issue?:
(max. 140 chars, 140 left)
```

then

```
Please choose a policy for the new issue:
```

and then

```
Enter a title for your innitiative:
(max. 140 chars, 140 left)
```

**Comment by nktc** [comment]
On my way to attacking this issue.  Pausing to note that `issue.name` was (rather oddly) overridden in the Issue model to point to policy name.  See:

https://github.com/Socioneers/LiquidVoting/blob/master/frontend/model/issue.lua#L285

I removed this code, which means that anywhere in the app that contains `issue.name` will now print out the Issue name, rather than the associated Policy name.

Additionally - `Issue.name` is a field I had to add to the database because it did not exist (as noted above, `policy.name` was previously being used for this purpose).

Hope that explanation makes sense, let me know if any questions.

Update:  Newly-created issues now have the option to add a name.

**Comment by kvdmolen** [comment]
Cool! Really nice work.

Though strangely, in the breadcrumb the "old" title remains (policyname & #id): http://178.62.254.91/lf/issue/show/15.html ("VeryQuickResolution 15")

Also in the index page: http://178.62.254.91/lf/index/index.html

Please check!

**Comment by nktc** [comment]
Done.  (Due to code duplication I needed change this in a few other places.)
